# **Tarea Nº 1**

Curso:          Fundamentos de Programación en Python
Profesor:       Victor Fuentes Campos     

- Fecha y hora de entrega: Domingo Jueves 1 de dicieimbre, 11:59pm
- Agregue los nombres de las personas con las que discutió esta tarea: ____ Gabriel Vargas ______
- Envíe su tarea haciendo el `push` de su código a su repo en GitHub Classroom: 

# 1. Git


a. Commit, Push, Pull

Instrucciones:
1. Cada miembro del equipo debe clonar el repo de su tarea en su computadora
1. Luego, en el branch master (`main`), el integrante Nº 1 cambia el nombre del archivo `.ipynb` a `tarea_1.ipynb`
1. Usando GitHub Desktop, el integrante Nº 2 notará que hay cambios en el repo. Por lo tanto, hará el `pull` de la nueva versión del repo. Ahora ambos tiene el archivo con el nombre apropiado en sus computadoras

*Este ejercicio se calificará directamente en GitHub*

b. Merge conflicts (opcional)

1. El integrante Nº 1 abre un branch nuevo `merge_conflict_practice_1`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 2 abre un branch nuevo `merge_conflict_practice_2`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 1 hará un `pull request`
1. El integrante Nº 2 hará el `review` del `pull request`, aceptará los cambios de su compañero y hará `merge` del branch al `master`. ¡Listo, completaste tu primer pull request!
1. El integrante Nº 2 hará un `pull request`
1. El integrante Nº 1 hará el `review` del `pull request` y habrá un `merge conflict` poeque ambos están cambiando la misma línea de código. Ajuste el archivo y complete el `merge``
Cambie de roles y fuerce un `merge conflict` con una sección diferente del archivo `tarea_1.ipynb` (Fecha de entrega, nombre del curso, etc.)
1. Explique muy brevemente porque se generó el `merge conflict`

*Respuesta: ______________________________*

# 2. Variables

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [1]:
monthly_savings = 10
num_months = 12

a. Calculate year_savings using monthly_savings and num_months


In [4]:
# Calculate the product of monthly_savings and num_months
years_savings= monthly_savings*num_months
print(years_savings)

120


b. Print the type of year_savings

In [5]:
# What do you think the resulting type will be? Find out by printing out the type of year_savings.
type(years_savings)

int

# 3. Lists

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [7]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.6 MB 14.0 MB/s eta 0:00:01
   ------------------- -------------------- 6.0/12.6 MB 14.2 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 13.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np
f_list = ["Brazil", np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']
p1_list = [ 2 , 3, 4, 5 , 6 ]
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1, 91 ]
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER", "MORALES CHOQUEHUANCA, ANGELICA KARINA", "GUIMARAY RIBEYRO, JOSE ROBERTO", "CAMACHO GAVIDIA, ABEL FERNANDO", "TINTAYA ORIHUELA, MEIR ALVARO", "CHAVEZ MARTINEZ, JOSELIN ALEXANDRA", "FIGUEROA MURO, LEONEL ARTURO", "GOMEZ CRIBILLERO, JOSE FELIPE", "PALOMINO SEGUÍN, AFRANIA", "LUZON CUEVA, BIANCA MARIETTE", "SUAÑA ZEGARRA, ADRIAN ANDRE", "SOTO POMACHAGUA, DORKAS YOMIRA JHERMY", "FIORENTINO MARTINEZ, LADY ALY", "LAMA MAVILA, HECTOR ANDRE", "MEZA HINOJO, GUSTAVO", "LOZADA MURILLO, PERSEO MARCELO", "ZAMBRANO JIMENEZ, MIGUEL ALONZO", "JACOBS LUQUE, NICOLAS", "VIDAL VIDAL, ROCIO GABRIELA", "TORRES ANICAMA, JANE CAMILA", "LOPEZ ESTRADA, MARIA ELISA", "BOYCO ORAMS, ALEJANDRO", "DIAZ BERROSPI, KARLINE ROSMELI", "RIEGA ESCALANTE, STEPHY ROSARIO", "LEVANO TORRES, VALERIA CECILIA", "ESQUIVES BRAVO, SEBASTIAN RENATO", "PEREZ GONZALES, JUAN CARLOS", "OTERO MAGUIÑA, MARIANA", "CLAVO CAMPOS, ANDREA BRIZETH", "AGUILAR GARCIA, ERICK JOSUE", "CALDAS VELASQUEZ, JOSUE DANIEL", "SALAS NUÑEZ BORJA, FABIO MANUEL", "PIZARRO VILLANES, FERNANDA NICOLLE", "QUILLATUPA MORALES, ANGELA ADELINA", "HUANCAYA IDONE, CESAR DANTE", "CALVO PORTOCARRERO, GABRIELA ISABEL", "IBAÑEZ ABANTO, ANGEL MAURICIO", "MELÉNDEZ APONTE, JUAN DIEGO", "CRISTIAN SERRANO, ARONE", "HINOJOSA CAHUANA, PERCY ALBERTH", "ANGLAS GARCÍA, KEVIN ARTURO", "ALDAVE ACOSTA, CESAR ERNESTO", "NÚÑEZ HUAMÁN, CÉSAR AGUSTO", "OBREGON HUAMAN, DIANA EDITH", "SOTO PACHERRES, RODRIGO FRANCO", "INGARUCA RIVERA, GRETTEL ALEXANDRA", "ROJAS HUAMAN, ROSA ANGELA", "NEYRA SALAS, DANTE OMAR", "HUERTA ESPINOZA, YAJAIRA ALEXANDRA", "HUANCA MARTINEZ, JORGE ALBERTO", "FLORES CADILLO, ALEXIS" ]
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe", "", "", "", "", "", "f0873079@pucp.edu.pe", "", "", "", "", "", "", "", "", "", "", "flores.alexis@pucp.edu.pe", ]

a. Show the indices of the `np.nan`` values in the `f_list` list. We want to see this output: *The indices 1, 2, 5, 8 have np.nan values*. Hint: Use print function and f-strings to insert the indices values.

In [30]:
# Show indices for np.nan values


b. Replicate 4 times the values of the list `p1_list`. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.

In [21]:
# Replicates p1_list
n = 4
p1_list_r = (p1_list)* n 
print(p1_list_r)

[2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6]


c. Print the length of `f_list`. **Hint: Length function**

In [10]:
# Lenngth of f_list
len(f_list)

9

d. Print `My new teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**

In [14]:
# Printing
' '.join(text1)

'My new teacher assistant is so boring.'

# 4. Strings

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [15]:
str1 = 'I am                            too                                                        old'
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]

1. Drop the duplicated blank spaces in `str1`. Do not use the regular expresions. Do not use the code shown in class. Explain your steps.**Hint: Use `split` method and `join` function.**

In [56]:
# Drop duplicated blank spaces
separar=str1.split()
print(separar)
juntar=(" ").join(separar)
print(juntar)

['I', 'am', 'too', 'old']
I am too old


2. Get the number of letters in the string .**Hint: Use `len`function.**

In [ ]:
# Number of letters
letters_only=[char for char in str1 if char.isalpha()]
num_letters=len(letters_only)
print(num_letters)

9


3. (Optional) Get the number of blank spaces (all of them) in the string .**Hint: Use `len`function.**

In [ ]:
# Number of blanck spaces (en str1)
blank_only=str1.count(" ")
print(blank_only)

85


In [57]:
# número de espacios en blacno en la versión junta
blank_only2=juntar.count(" ")
print(blank_only2)

3


# 5. NumPy

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [16]:
prueba1 = np.random.randint(0,15,1000)
prueba1


array([12, 10,  9,  1,  2, 13,  3,  8,  0, 10, 10,  7,  3,  4, 11,  2,  7,
        4, 14,  6,  1,  1,  5, 14,  0,  1, 13,  1, 13,  5, 14,  9,  5,  8,
        8, 10,  3,  3,  0, 14, 14,  4,  8,  9,  6, 11,  3, 12, 12,  3,  7,
        7,  3, 14, 13, 13,  7,  8, 10,  9,  0, 10, 12,  8, 11,  6,  6, 14,
        7, 11,  7, 12,  8, 13, 10,  3, 11,  4, 12, 10, 12,  8, 12,  1, 11,
        1,  7,  6, 13,  6,  4,  7,  8, 10, 11,  5, 12,  8,  2, 10,  5, 11,
       13,  1, 14,  7,  9,  9, 10,  0,  7,  1, 13,  2,  9,  2,  0,  0,  5,
        7,  7,  1,  3, 14,  2,  1,  4,  1,  8,  8,  0,  5, 11,  7, 12,  8,
        1,  6,  4,  3,  4,  2,  9, 13,  7, 10,  4, 10,  5,  1,  5,  8,  2,
        0, 11,  2,  8,  1,  0, 12, 10,  9,  5, 12, 13,  6,  1,  5,  4,  0,
        6,  5, 14,  8, 12,  3,  4, 12,  2, 11, 14, 11, 13,  0, 12,  1,  6,
        1,  9,  9,  8, 10,  8,  5,  9, 13, 10,  2, 12,  0,  2, 14,  7, 11,
        0,  9, 12, 11,  3, 13,  4, 10,  8,  1, 14, 14,  3, 13,  3,  8, 14,
        5,  9,  9,  2,  1

In [17]:
prueba2 = np.arange(50)
np.random.shuffle(prueba2)
prueba2

array([43, 22, 15, 42, 45, 10, 47,  2,  3, 34,  4,  6,  8, 33, 31, 48, 39,
       40, 41,  7, 28, 24, 27,  5, 49, 36, 19, 23, 37, 35, 11, 20, 12, 29,
       38, 46, 44,  9, 21, 32,  0, 25, 18, 17, 16, 30,  1, 14, 26, 13])

a. Find the most frequent value in the prueba1 array?

In [29]:
# Most frequent value
values, counts = np.unique(prueba1, return_counts=True)
mode = values[np.argmax(counts)]
print(f"Moda: {mode}")


Moda: 5


b. Convert the 1D array prueba2 to a 2D array with 5 rows

In [20]:
# Reshape
prueba2_2D=prueba2.reshape(5,10)
prueba2_2D

array([[43, 22, 15, 42, 45, 10, 47,  2,  3, 34],
       [ 4,  6,  8, 33, 31, 48, 39, 40, 41,  7],
       [28, 24, 27,  5, 49, 36, 19, 23, 37, 35],
       [11, 20, 12, 29, 38, 46, 44,  9, 21, 32],
       [ 0, 25, 18, 17, 16, 30,  1, 14, 26, 13]])

# 6. Pandas

Utilice la base de datos `nyc_taxis.csv`

Let's work with a subset of the New York City taxi trip data released by the city. We'll focus on about 90,000 yellow taxi trips to and from various NYC airports between January and June 2016. Here are some selected columns from the dataset:

- `pickup_month`: the month of the trip (January is 1, December is 12)
- `pickup_day`: the day of the month of the trip
- `pickup_location_code`: the airport or borough where the trip started
- `dropoff_location_code`: the airport or borough where the trip ended
- `trip_distance`: the distance of the trip in miles
- `trip_length`: the length of the trip in seconds
- `fare_amount`: the base fare of the trip, in dollars
- `total_amount`: the total amount charged to the passenger, including all fees, tolls, and tips


Review the dictionary data [here](https://s3.amazonaws.com/dq-content/289/nyc_taxi_data_dictionary.md).

Our data is stored in a CSV file called `nyc_taxis.csv`


Calcule:
1. El promedio de la distancia de viaje (`trip_distance`) para cada mes (`pickup_month`)
2. Cantidad de viajes desde JFK por día del mes