# **Tarea Nº 1**

Curso:          Fundamentos de Programación en Python
Profesor:       Victor Fuentes Campos     

- Fecha y hora de entrega: Domingo Jueves 1 de dicieimbre, 11:59pm
- Agregue los nombres de las personas con las que discutió esta tarea: Margarita Mamani Condori_
- linea creada para generar conflicto
- Envíe su tarea haciendo el `push` de su código a su repo en GitHub Classroom: 

# 1. Git


a. Commit, Push, Pull

Instrucciones:
1. Cada miembro del equipo debe clonar el repo de su tarea en su computadora
1. Luego, en el branch master (`main`), el integrante Nº 1 cambia el nombre del archivo `.ipynb` a `tarea_1.ipynb`
1. Usando GitHub Desktop, el integrante Nº 2 notará que hay cambios en el repo. Por lo tanto, hará el `pull` de la nueva versión del repo. Ahora ambos tiene el archivo con el nombre apropiado en sus computadoras

*Este ejercicio se calificará directamente en GitHub*

b. Merge conflicts (opcional)

1. El integrante Nº 1 abre un branch nuevo `merge_conflict_practice_1`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 2 abre un branch nuevo `merge_conflict_practice_2`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 1 hará un `pull request`
1. El integrante Nº 2 hará el `review` del `pull request`, aceptará los cambios de su compañero y hará `merge` del branch al `master`. ¡Listo, completaste tu primer pull request!
1. El integrante Nº 2 hará un `pull request`
1. El integrante Nº 1 hará el `review` del `pull request` y habrá un `merge conflict` poeque ambos están cambiando la misma línea de código. Ajuste el archivo y complete el `merge``
Cambie de roles y fuerce un `merge conflict` con una sección diferente del archivo `tarea_1.ipynb` (Fecha de entrega, nombre del curso, etc.)
1. Explique muy brevemente porque se generó el `merge conflict`

*Respuesta: El conflicto se realizo por que ambas hicimos el cambio en la misma linea. En mi caso coloque mi nombre y mi compañera coloco su nombre, pero ambas en linea. 

# 2. Variables

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [1]:
monthly_savings = 10
num_months = 12

a. Calculate year_savings using monthly_savings and num_months


In [2]:
# Calculate the product of monthly_savings and num_months
producto=monthly_savings*12

b. Print the type of year_savings

In [3]:
# What do you think the resulting type will be? Find out by printing out the type of year_savings.
print(producto)

120


# 3. Lists

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [8]:
import numpy as np
f_list = ["Brazil", np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']
p1_list = [ 2 , 3, 4, 5 , 6 ]
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1, 91 ]
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER", "MORALES CHOQUEHUANCA, ANGELICA KARINA", "GUIMARAY RIBEYRO, JOSE ROBERTO", "CAMACHO GAVIDIA, ABEL FERNANDO", "TINTAYA ORIHUELA, MEIR ALVARO", "CHAVEZ MARTINEZ, JOSELIN ALEXANDRA", "FIGUEROA MURO, LEONEL ARTURO", "GOMEZ CRIBILLERO, JOSE FELIPE", "PALOMINO SEGUÍN, AFRANIA", "LUZON CUEVA, BIANCA MARIETTE", "SUAÑA ZEGARRA, ADRIAN ANDRE", "SOTO POMACHAGUA, DORKAS YOMIRA JHERMY", "FIORENTINO MARTINEZ, LADY ALY", "LAMA MAVILA, HECTOR ANDRE", "MEZA HINOJO, GUSTAVO", "LOZADA MURILLO, PERSEO MARCELO", "ZAMBRANO JIMENEZ, MIGUEL ALONZO", "JACOBS LUQUE, NICOLAS", "VIDAL VIDAL, ROCIO GABRIELA", "TORRES ANICAMA, JANE CAMILA", "LOPEZ ESTRADA, MARIA ELISA", "BOYCO ORAMS, ALEJANDRO", "DIAZ BERROSPI, KARLINE ROSMELI", "RIEGA ESCALANTE, STEPHY ROSARIO", "LEVANO TORRES, VALERIA CECILIA", "ESQUIVES BRAVO, SEBASTIAN RENATO", "PEREZ GONZALES, JUAN CARLOS", "OTERO MAGUIÑA, MARIANA", "CLAVO CAMPOS, ANDREA BRIZETH", "AGUILAR GARCIA, ERICK JOSUE", "CALDAS VELASQUEZ, JOSUE DANIEL", "SALAS NUÑEZ BORJA, FABIO MANUEL", "PIZARRO VILLANES, FERNANDA NICOLLE", "QUILLATUPA MORALES, ANGELA ADELINA", "HUANCAYA IDONE, CESAR DANTE", "CALVO PORTOCARRERO, GABRIELA ISABEL", "IBAÑEZ ABANTO, ANGEL MAURICIO", "MELÉNDEZ APONTE, JUAN DIEGO", "CRISTIAN SERRANO, ARONE", "HINOJOSA CAHUANA, PERCY ALBERTH", "ANGLAS GARCÍA, KEVIN ARTURO", "ALDAVE ACOSTA, CESAR ERNESTO", "NÚÑEZ HUAMÁN, CÉSAR AGUSTO", "OBREGON HUAMAN, DIANA EDITH", "SOTO PACHERRES, RODRIGO FRANCO", "INGARUCA RIVERA, GRETTEL ALEXANDRA", "ROJAS HUAMAN, ROSA ANGELA", "NEYRA SALAS, DANTE OMAR", "HUERTA ESPINOZA, YAJAIRA ALEXANDRA", "HUANCA MARTINEZ, JORGE ALBERTO", "FLORES CADILLO, ALEXIS" ]
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe", "", "", "", "", "", "f0873079@pucp.edu.pe", "", "", "", "", "", "", "", "", "", "", "flores.alexis@pucp.edu.pe", ]

a. Show the indices of the `np.nan`` values in the `f_list` list. We want to see this output: *The indices 1, 2, 5, 8 have np.nan values*. Hint: Use print function and f-strings to insert the indices values.

In [30]:
# Show indices for np.nan values
np.nan=[1,2,5,8]
print(np.nan)

[1, 2, 5, 8]


In [32]:
print(["Brazil", f"1" , f"2", "Austria", "Germany", f"5", "Pakistan", "np.nan", f"8" ])

['Brazil', '1', '2', 'Austria', 'Germany', '5', 'Pakistan', 'np.nan', '8']


b. Replicate 4 times the values of the list `p1_list`. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.

In [25]:
# Replicates p1_list
newp1_list=p1_list*4
print(newp1_list)


[2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6]


c. Print the length of `f_list`. **Hint: Length function**

In [16]:
# Lenngth of f_list
longitud=len(f_list)
print(longitud)

9


d. Print `My new teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**


In [18]:
' '.join(text1)

'My new teacher assistant is so boring.'

# 4. Strings

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [ ]:
str1 = 'I am                            too                                                        old'
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]

1. Drop the duplicated blank spaces in `str1`. Do not use the regular expresions. Do not use the code shown in class. Explain your steps.**Hint: Use `split` method and `join` function.**

In [75]:
# Drop duplicated blank spaces
str1 = 'I am                            too                                                        old'
str2 = " ".join(str1.split())
print(str2)

I am too old


2. Get the number of letters in the string .**Hint: Use `len`function.**

In [83]:
# Number of letters
palabras=str2.split()
print(palabras)
numero_de_palabras=len(palabras)
print("Número de palabras en la oración:", numero_de_palabras)

['I', 'am', 'too', 'old']
Número de palabras en la oración: 4


3. (Optional) Get the number of blank spaces (all of them) in the string .**Hint: Use `len`function.**

In [100]:
# Number of blanck spaces
str1 = 'I am                            too                                                        old'
espacios_blanco= " "
if espacios_blanco in str1:
    print("Tenemos {} espacios en blanco dentro del string".format(str1.count(espacios_blanco)))

Tenemos 85 espacios en blanco dentro del string


# 5. NumPy

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [103]:
prueba1 = np.random.randint(0,15,1000)
prueba1


array([ 8,  4,  6,  7,  3,  3, 14, 13, 12, 13, 14, 13, 10,  6, 14,  7,  5,
        5,  6,  6,  3,  6,  3,  9,  7,  4,  6,  2, 10, 11,  9,  2,  6,  4,
        3,  4, 12,  0, 10, 11, 11,  6, 10,  1, 10,  5,  7,  9,  2,  7,  6,
       14, 14,  7, 12, 14,  4,  8,  5,  9, 14,  9, 12, 10,  6,  1, 10, 14,
        9, 12,  4,  6,  4, 13,  5,  4, 14,  5,  5,  4,  0,  9,  8,  2,  5,
        9,  2,  4, 13,  4, 10, 12,  7,  0,  5,  5,  5, 10, 11,  7, 11,  4,
        3, 10, 14,  7,  3,  3, 10, 13,  8,  3,  9, 14,  0, 10,  5, 10,  8,
        6,  6,  0,  5,  5,  3,  0,  1, 13, 11,  3,  8,  5, 12, 11,  4,  3,
       14,  4,  0,  0,  4,  9, 12, 13, 13,  1, 14,  0,  9, 10,  2,  2, 12,
        0,  9, 13,  8,  5,  3,  1, 12,  7,  0, 12,  3,  9, 10,  6, 13,  4,
        5,  5,  5, 13,  3, 14,  2,  0,  2, 11, 10,  3,  5,  0,  3, 14,  0,
        1, 10, 14, 10, 12,  8, 11, 10,  2,  4,  0,  7,  9, 10,  0,  0, 14,
       14,  2, 14, 13,  6, 13,  3, 12, 13,  7,  7,  3, 10,  4,  3,  8,  2,
        8, 13,  0,  2, 14

In [118]:
prueba2 = np.arange(50)
np.random.shuffle(prueba2)
prueba2

array([41, 17,  5, 19,  4, 18, 29,  9, 46, 37, 10, 24, 31, 25, 48,  0, 44,
       21,  3, 43, 34, 36,  6, 45, 20, 38, 14, 26, 15, 32, 12, 28, 27, 49,
       11, 35, 23, 40, 22, 30,  2, 13, 39,  8, 16, 47, 33, 42,  1,  7])

a. Find the most frequent value in the prueba1 array?

In [127]:
# Most frequent value
valores, conteos= np.unique(prueba1, return_counts=True)
valores
conteos
valores[np.argmax(conteos)]

np.int32(3)

b. Convert the 1D array prueba2 to a 2D array with 5 rows

In [125]:
# Reshape
arr1=prueba2.reshape(5, 10)
print('Despues del reshape se tiene una dimensión 5x1')
print(arr1)
print('\n')

Despues del reshape se tiene una dimensión 5x1
[[42 33 45 39 46 47 19 31  2 49]
 [11 10 21 20 14  8 29  6 43 26]
 [15 30  4  7 37 13 34 25 23 32]
 [35 24  3 40 16 38 22 48 18  0]
 [28 27  5 17 36  1  9 12 41 44]]




In [128]:
prueba2_2D = np.reshape(prueba2, (5, 10))
print("Arreglo 2D:")
print(prueba2_2D)

Arreglo 2D:
[[42 33 45 39 46 47 19 31  2 49]
 [11 10 21 20 14  8 29  6 43 26]
 [15 30  4  7 37 13 34 25 23 32]
 [35 24  3 40 16 38 22 48 18  0]
 [28 27  5 17 36  1  9 12 41 44]]


# 6. Pandas

Utilice la base de datos `nyc_taxis.csv`

Let's work with a subset of the New York City taxi trip data released by the city. We'll focus on about 90,000 yellow taxi trips to and from various NYC airports between January and June 2016. Here are some selected columns from the dataset:

- `pickup_month`: the month of the trip (January is 1, December is 12)
- `pickup_day`: the day of the month of the trip
- `pickup_location_code`: the airport or borough where the trip started
- `dropoff_location_code`: the airport or borough where the trip ended
- `trip_distance`: the distance of the trip in miles
- `trip_length`: the length of the trip in seconds
- `fare_amount`: the base fare of the trip, in dollars
- `total_amount`: the total amount charged to the passenger, including all fees, tolls, and tips


Review the dictionary data [here](https://s3.amazonaws.com/dq-content/289/nyc_taxi_data_dictionary.md).

Our data is stored in a CSV file called `nyc_taxis.csv`


Calcule:
1. El promedio de la distancia de viaje (`trip_distance`) para cada mes (`pickup_month`)
2. Cantidad de viajes desde JFK por día del mes