# **Tarea Nº 1**

Curso:          Fundamentos de Programación en Python
Profesor:       Victor Fuentes Campos     

- Fecha y hora de entrega: Domingo Jueves 1 de dicieimbre, 11:59pm
- Agregue los nombres de las personas con las que discutió esta tarea: Saby Sanchez
- Envíe su tarea haciendo el `push` de su código a su repo en GitHub Classroom: 
- Curso :  de Capacitación en Fundamentos de Python para CCSS y Gestión Pública 2024-02

# 1. Git


a. Commit, Push, Pull

Instrucciones:
1. Cada miembro del equipo debe clonar el repo de su tarea en su computadora
1. Luego, en el branch master (`main`), el integrante Nº 1 cambia el nombre del archivo `.ipynb` a `tarea_1.ipynb`
1. Usando GitHub Desktop, el integrante Nº 2 notará que hay cambios en el repo. Por lo tanto, hará el `pull` de la nueva versión del repo. Ahora ambos tiene el archivo con el nombre apropiado en sus computadoras

*Este ejercicio se calificará directamente en GitHub*

b. Merge conflicts (opcional)

1. El integrante Nº 1 abre un branch nuevo `merge_conflict_practice_1`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 2 abre un branch nuevo `merge_conflict_practice_2`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 1 hará un `pull request`
1. El integrante Nº 2 hará el `review` del `pull request`, aceptará los cambios de su compañero y hará `merge` del branch al `master`. ¡Listo, completaste tu primer pull request!
1. El integrante Nº 2 hará un `pull request`
1. El integrante Nº 1 hará el `review` del `pull request` y habrá un `merge conflict` poeque ambos están cambiando la misma línea de código. Ajuste el archivo y complete el `merge``
Cambie de roles y fuerce un `merge conflict` con una sección diferente del archivo `tarea_1.ipynb` (Fecha de entrega, nombre del curso, etc.)
1. Explique muy brevemente porque se generó el `merge conflict`

Respuesta: El merge conflict se generó porque ambos integrantes realizaron cambios en la misma línea de código (en este caso, reemplazaron "Armando Paredes" por nuestros nombres) en ramas diferentes y luego intentamos combinar esos cambios en la rama principal (master). Git no puede resolver automáticamente cuál de los cambios debe conservarse, ya que los considera contradictorios, lo que requiere intervención manual para decidir cómo fusionar el archivo

# 2. Variables

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [13]:
monthly_savings = 10
num_months = 12

a. Calculate year_savings using monthly_savings and num_months

In [14]:
# Calculate the product of monthly_savings and num_months
year_savings = monthly_savings * num_months
print (year_savings)

120


b. Print the type of year_savings

In [15]:
# What do you think the resulting type will be? Find out by printing out the type of year_savings.
print(type(year_savings))

<class 'int'>


# 3. Lists

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [16]:
import numpy as np
f_list = ["Brazil", np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']
p1_list = [ 2 , 3, 4, 5 , 6 ]
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1, 91 ]
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER", "MORALES CHOQUEHUANCA, ANGELICA KARINA", "GUIMARAY RIBEYRO, JOSE ROBERTO", "CAMACHO GAVIDIA, ABEL FERNANDO", "TINTAYA ORIHUELA, MEIR ALVARO", "CHAVEZ MARTINEZ, JOSELIN ALEXANDRA", "FIGUEROA MURO, LEONEL ARTURO", "GOMEZ CRIBILLERO, JOSE FELIPE", "PALOMINO SEGUÍN, AFRANIA", "LUZON CUEVA, BIANCA MARIETTE", "SUAÑA ZEGARRA, ADRIAN ANDRE", "SOTO POMACHAGUA, DORKAS YOMIRA JHERMY", "FIORENTINO MARTINEZ, LADY ALY", "LAMA MAVILA, HECTOR ANDRE", "MEZA HINOJO, GUSTAVO", "LOZADA MURILLO, PERSEO MARCELO", "ZAMBRANO JIMENEZ, MIGUEL ALONZO", "JACOBS LUQUE, NICOLAS", "VIDAL VIDAL, ROCIO GABRIELA", "TORRES ANICAMA, JANE CAMILA", "LOPEZ ESTRADA, MARIA ELISA", "BOYCO ORAMS, ALEJANDRO", "DIAZ BERROSPI, KARLINE ROSMELI", "RIEGA ESCALANTE, STEPHY ROSARIO", "LEVANO TORRES, VALERIA CECILIA", "ESQUIVES BRAVO, SEBASTIAN RENATO", "PEREZ GONZALES, JUAN CARLOS", "OTERO MAGUIÑA, MARIANA", "CLAVO CAMPOS, ANDREA BRIZETH", "AGUILAR GARCIA, ERICK JOSUE", "CALDAS VELASQUEZ, JOSUE DANIEL", "SALAS NUÑEZ BORJA, FABIO MANUEL", "PIZARRO VILLANES, FERNANDA NICOLLE", "QUILLATUPA MORALES, ANGELA ADELINA", "HUANCAYA IDONE, CESAR DANTE", "CALVO PORTOCARRERO, GABRIELA ISABEL", "IBAÑEZ ABANTO, ANGEL MAURICIO", "MELÉNDEZ APONTE, JUAN DIEGO", "CRISTIAN SERRANO, ARONE", "HINOJOSA CAHUANA, PERCY ALBERTH", "ANGLAS GARCÍA, KEVIN ARTURO", "ALDAVE ACOSTA, CESAR ERNESTO", "NÚÑEZ HUAMÁN, CÉSAR AGUSTO", "OBREGON HUAMAN, DIANA EDITH", "SOTO PACHERRES, RODRIGO FRANCO", "INGARUCA RIVERA, GRETTEL ALEXANDRA", "ROJAS HUAMAN, ROSA ANGELA", "NEYRA SALAS, DANTE OMAR", "HUERTA ESPINOZA, YAJAIRA ALEXANDRA", "HUANCA MARTINEZ, JORGE ALBERTO", "FLORES CADILLO, ALEXIS" ]
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe", "", "", "", "", "", "f0873079@pucp.edu.pe", "", "", "", "", "", "", "", "", "", "", "flores.alexis@pucp.edu.pe", ]

a. Show the indices of the `np.nan`` values in the `f_list` list. We want to see this output: *The indices 1, 2, 5, 8 have np.nan values*. Hint: Use print function and f-strings to insert the indices values.

In [18]:
# Show indices for np.nan values
np.nan = [1,2,5,8]
print (np.nan)

[1, 2, 5, 8]


b. Replicate 4 times the values of the list `p1_list`. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.

In [19]:
# Replicates p1_list
print(["Brazil", f"1" , f"2" , "Austria","Germany" , f"5" , "Pakistan" , "np.nan" ,"8" ])

['Brazil', '1', '2', 'Austria', 'Germany', '5', 'Pakistan', 'np.nan', '8']


c. Print the length of `f_list`. **Hint: Length function**

In [20]:
# Lenngth of f_list
print(len(f_list))


9


d. Print `My new teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**

In [23]:
# Printing
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']

result = ' '.join(text1)

print(result)


My new teacher assistant is so boring.


# 4. Strings

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [43]:
str1 = 'I am                            too                                                        old'


1. Drop the duplicated blank spaces in `str1`. Do not use the regular expresions. Do not use the code shown in class. Explain your steps.**Hint: Use `split` method and `join` function.**

In [36]:
# Drop duplicated blank spaces
str2 = ' '.join(str1.split())

print(str2)

I am too old


2. Get the number of letters in the string .**Hint: Use `len`function.**

In [37]:
print(str2)

I am too old


In [41]:
# Number of letters

palabras = str2.split()
print(palabras)
num_letters = len(palabras)
print("Número de palabras en la oración:",num_letters)

['I', 'am', 'too', 'old']
Número de palabras en la oración: 4


3. (Optional) Get the number of blank spaces (all of them) in the string .**Hint: Use `len`function.**

In [48]:
# Number of blanck spaces
str1 = 'I am                            too                                                        old'

espacios_blanco= " "

if espacios_blanco in str1:
    print("Tenemos {} espacios en blanco dentro del string".format(str1.count(espacios_blanco)))

Tenemos 85 espacios en blanco dentro del string


# 5. NumPy

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [56]:
prueba1 = np.random.randint(0,15,1000)
prueba1


array([ 9, 11,  6,  7, 12,  7,  9, 12, 11, 11, 14,  8, 10,  4, 10, 11,  5,
       12, 11,  5,  8, 10,  2,  3,  7, 10,  7,  0,  2, 12,  7,  0,  7,  8,
       14,  1, 10,  7,  8,  0,  4, 14,  7,  6, 14,  2, 14, 14, 10,  2,  5,
       14,  2, 13,  9,  7, 12,  2, 13, 14,  5,  9, 13,  9,  0,  3,  5, 13,
        7, 13,  5, 10, 14, 11, 11, 12,  1,  3, 12,  1,  3, 11, 13, 12, 12,
       11,  7, 13,  9,  3,  0,  4,  2,  8,  4,  8,  8,  1,  8,  1, 11, 13,
        5,  2,  6,  7, 11,  7,  1,  5, 12,  0, 13,  8, 11,  4, 11,  4,  5,
       13,  0,  9,  3,  1, 14,  3,  2,  5,  1,  5, 10,  5,  0,  6,  7,  9,
        4,  4,  9, 12, 11,  9,  0, 11,  4,  8,  3,  7,  5,  8,  1,  8,  9,
        9, 12,  2,  0,  2,  9, 10,  7,  7,  1,  7,  7, 11,  6, 12,  9,  2,
        1, 10, 10,  2,  7, 11,  6, 12,  0,  5,  7,  8,  6, 14, 12,  4,  6,
       11,  6,  8,  9,  5, 13,  9,  6,  0, 10,  9,  2, 12,  4, 10,  5, 14,
        4,  4, 13,  4,  9, 11, 14,  8, 14,  3,  7,  2,  4, 11, 12, 13,  3,
        9,  4, 13, 14, 10

In [61]:
prueba2 = np.arange(50)
np.random.shuffle(prueba2)
prueba2

array([ 2, 49, 38,  8, 33, 28, 24,  7,  1, 16, 47, 37, 23, 46,  0, 17, 31,
       42, 10, 25,  6, 29, 15,  5, 40, 36, 43, 45, 21, 39, 48, 32,  4, 30,
       14,  3, 22, 13, 34, 44, 26, 41, 35, 19, 11, 18, 12,  9, 20, 27])

a. Find the most frequent value in the prueba1 array?

In [62]:
# Most frequent value
valores, conteos= np.unique(prueba1, return_counts=True)
valores
conteos
valores [np.argmax(conteos)]

np.int64(4)

b. Convert the 1D array prueba2 to a 2D array with 5 rows

In [63]:
# Reshape
prueba2_2D = np.reshape(prueba2, (5, 10))
print("Arreglo 2D:")
print(prueba2_2D)

Arreglo 2D:
[[ 2 49 38  8 33 28 24  7  1 16]
 [47 37 23 46  0 17 31 42 10 25]
 [ 6 29 15  5 40 36 43 45 21 39]
 [48 32  4 30 14  3 22 13 34 44]
 [26 41 35 19 11 18 12  9 20 27]]


# 6. Pandas

Utilice la base de datos `nyc_taxis.csv`

Let's work with a subset of the New York City taxi trip data released by the city. We'll focus on about 90,000 yellow taxi trips to and from various NYC airports between January and June 2016. Here are some selected columns from the dataset:

- `pickup_month`: the month of the trip (January is 1, December is 12)
- `pickup_day`: the day of the month of the trip
- `pickup_location_code`: the airport or borough where the trip started
- `dropoff_location_code`: the airport or borough where the trip ended
- `trip_distance`: the distance of the trip in miles
- `trip_length`: the length of the trip in seconds
- `fare_amount`: the base fare of the trip, in dollars
- `total_amount`: the total amount charged to the passenger, including all fees, tolls, and tips


Review the dictionary data [here](https://s3.amazonaws.com/dq-content/289/nyc_taxi_data_dictionary.md).

Our data is stored in a CSV file called `nyc_taxis.csv`


Calcule:
1. El promedio de la distancia de viaje (`trip_distance`) para cada mes (`pickup_month`)
2. Cantidad de viajes desde JFK por día del mes